Search.appendIndex(
    [
                {
            "fqsen": "\\MatthiasMullie\\Router\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Exception.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Exception\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Exception.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Exception\u003A\u003AgetStatusCode\u0028\u0029",
            "name": "getStatusCode",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Exception.html#method_getStatusCode"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Exception\u003A\u003AgetHeaders\u0028\u0029",
            "name": "getHeaders",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Exception.html#method_getHeaders"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\ExceptionResponse",
            "name": "ExceptionResponse",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-ExceptionResponse.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\ExceptionResponse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-ExceptionResponse.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\ExceptionResponse\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-ExceptionResponse.html#method_handle"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\ExceptionResponseInterface",
            "name": "ExceptionResponseInterface",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-ExceptionResponseInterface.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\ExceptionResponseInterface\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-ExceptionResponseInterface.html#method_handle"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Group",
            "name": "Group",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Group.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Group\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Group.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Group\u003A\u003AaddGroup\u0028\u0029",
            "name": "addGroup",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Group.html#method_addGroup"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Group\u003A\u003AaddMiddleware\u0028\u0029",
            "name": "addMiddleware",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Group.html#method_addMiddleware"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Group\u003A\u003AaddRoute\u0028\u0029",
            "name": "addRoute",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Group.html#method_addRoute"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Group\u003A\u003AgetRoutes\u0028\u0029",
            "name": "getRoutes",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Group.html#method_getRoutes"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\MiddlewareContainer",
            "name": "MiddlewareContainer",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-MiddlewareContainer.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\MiddlewareContainer\u003A\u003AaddMiddleware\u0028\u0029",
            "name": "addMiddleware",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-MiddlewareContainer.html#method_addMiddleware"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\MiddlewareContainer\u003A\u003AgetMiddleware\u0028\u0029",
            "name": "getMiddleware",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-MiddlewareContainer.html#method_getMiddleware"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\RequestMethods",
            "name": "RequestMethods",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-RequestMethods.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\RequestMethods\u003A\u003AGET",
            "name": "GET",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-RequestMethods.html#enumcase_GET"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\RequestMethods\u003A\u003AHEAD",
            "name": "HEAD",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-RequestMethods.html#enumcase_HEAD"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\RequestMethods\u003A\u003APOST",
            "name": "POST",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-RequestMethods.html#enumcase_POST"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\RequestMethods\u003A\u003APUT",
            "name": "PUT",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-RequestMethods.html#enumcase_PUT"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\RequestMethods\u003A\u003ADELETE",
            "name": "DELETE",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-RequestMethods.html#enumcase_DELETE"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\RequestMethods\u003A\u003ACONNECT",
            "name": "CONNECT",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-RequestMethods.html#enumcase_CONNECT"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\RequestMethods\u003A\u003AOPTIONS",
            "name": "OPTIONS",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-RequestMethods.html#enumcase_OPTIONS"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\RequestMethods\u003A\u003ATRACE",
            "name": "TRACE",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-RequestMethods.html#enumcase_TRACE"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\RequestMethods\u003A\u003APATCH",
            "name": "PATCH",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-RequestMethods.html#enumcase_PATCH"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Route",
            "name": "Route",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Route.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Route\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Route.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Route\u003A\u003AgetMethod\u0028\u0029",
            "name": "getMethod",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Route.html#method_getMethod"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Route\u003A\u003AgetPath\u0028\u0029",
            "name": "getPath",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Route.html#method_getPath"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Route\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Route.html#method_handle"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Router",
            "name": "Router",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Router.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Router\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Router.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Router\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Router.html#method_handle"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\Router\u003A\u003Aoutput\u0028\u0029",
            "name": "output",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-Router.html#method_output"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes",
            "name": "StatusCodes",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AContinue",
            "name": "Continue",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_Continue"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003ASwitchingProtocols",
            "name": "SwitchingProtocols",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_SwitchingProtocols"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AOk",
            "name": "Ok",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_Ok"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003ACreated",
            "name": "Created",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_Created"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AAccepted",
            "name": "Accepted",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_Accepted"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003ANonAuthoritativeInformation",
            "name": "NonAuthoritativeInformation",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_NonAuthoritativeInformation"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003ANoContent",
            "name": "NoContent",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_NoContent"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AResetContent",
            "name": "ResetContent",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_ResetContent"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003APartialContent",
            "name": "PartialContent",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_PartialContent"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AMultipleChoices",
            "name": "MultipleChoices",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_MultipleChoices"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AMovedPermanently",
            "name": "MovedPermanently",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_MovedPermanently"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AFound",
            "name": "Found",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_Found"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003ASeeOther",
            "name": "SeeOther",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_SeeOther"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003ANotModified",
            "name": "NotModified",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_NotModified"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AUseProxy",
            "name": "UseProxy",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_UseProxy"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003ASwitchProxy",
            "name": "SwitchProxy",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_SwitchProxy"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003ATemporaryRedirect",
            "name": "TemporaryRedirect",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_TemporaryRedirect"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003APermanentRedirect",
            "name": "PermanentRedirect",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_PermanentRedirect"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003ABadRequest",
            "name": "BadRequest",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_BadRequest"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AUnauthorized",
            "name": "Unauthorized",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_Unauthorized"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003APaymentRequired",
            "name": "PaymentRequired",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_PaymentRequired"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AForbidden",
            "name": "Forbidden",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_Forbidden"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003ANotFound",
            "name": "NotFound",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_NotFound"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AMethodNotAllowed",
            "name": "MethodNotAllowed",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_MethodNotAllowed"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003ANotAcceptable",
            "name": "NotAcceptable",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_NotAcceptable"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AProxyAuthenticationRequired",
            "name": "ProxyAuthenticationRequired",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_ProxyAuthenticationRequired"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003ARequestTimeout",
            "name": "RequestTimeout",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_RequestTimeout"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AConflict",
            "name": "Conflict",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_Conflict"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AGone",
            "name": "Gone",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_Gone"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003ALengthRequired",
            "name": "LengthRequired",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_LengthRequired"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003APreconditionFailed",
            "name": "PreconditionFailed",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_PreconditionFailed"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AContentTooLARGE",
            "name": "ContentTooLARGE",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_ContentTooLARGE"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AUriTooLong",
            "name": "UriTooLong",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_UriTooLong"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AUnsupportedMediaType",
            "name": "UnsupportedMediaType",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_UnsupportedMediaType"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003ARangeNotSatisfiable",
            "name": "RangeNotSatisfiable",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_RangeNotSatisfiable"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AExpectationFailed",
            "name": "ExpectationFailed",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_ExpectationFailed"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AImATeapot",
            "name": "ImATeapot",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_ImATeapot"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AMisdirectedRequest",
            "name": "MisdirectedRequest",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_MisdirectedRequest"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AUnprocessableContent",
            "name": "UnprocessableContent",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_UnprocessableContent"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AUpgradeRequired",
            "name": "UpgradeRequired",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_UpgradeRequired"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AInternalServerError",
            "name": "InternalServerError",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_InternalServerError"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003ANotImplemented",
            "name": "NotImplemented",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_NotImplemented"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003ABadGateway",
            "name": "BadGateway",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_BadGateway"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AServiceUnavailable",
            "name": "ServiceUnavailable",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_ServiceUnavailable"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AGatewayTimeout",
            "name": "GatewayTimeout",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_GatewayTimeout"
        },                {
            "fqsen": "\\MatthiasMullie\\Router\\StatusCodes\u003A\u003AHttpVersionNotSupported",
            "name": "HttpVersionNotSupported",
            "summary": "",
            "url": "classes/MatthiasMullie-Router-StatusCodes.html#enumcase_HttpVersionNotSupported"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Router",
            "name": "Router",
            "summary": "",
            "url": "namespaces/matthiasmullie-router.html"
        },                {
            "fqsen": "\\MatthiasMullie",
            "name": "MatthiasMullie",
            "summary": "",
            "url": "namespaces/matthiasmullie.html"
        }            ]
);
